service: aws-node-rest-api-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  environment:
    NODE_ENV: dev
    DB_HOST: bizzi_test
    DB_NAME: bizzi_test
    DB_USERNAME: admin
    DB_PASSWORD: YHCQ4n7PAvvuyvk3DWDc
    ALGOLIA_APP_ID: LMHMCNTV6H
    ALGOLIA_ADMIN_API_KEY: 2ed02b649b40c391c01a9fa8fa016a15
    ALGOLIA_INDEX: bizzi_app
    CORS_ORIGIN: http://localhost:3000
    ACCESS_TOKEN: SECRET=abcd
    REFRESH_TOKEN_SECRET: ddfdfdf

plugins:
  - serverless-plugin-typescript
  - serverless-offline
functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
