export const ERROR_CODE = {
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    UNAUTHORIZATION: 'UNAUTHORIZATION',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    NOT_FOUND: 'NOT_FOUND',
    DUPPLICATED: 'DUPPLICATED',
    VALIDATE_FAILED: 'VALIDATE_FAILED',
    SERVER_ERROR: 'SERVER_ERROR',
    INVALID: 'INVALID',

}

export const POST_STATUS = {
    ACTIVE: 1,
    INACTIVE: 0
}